name: ğŸ™Workflows MasterğŸ™
on:
  workflow_dispatch:
jobs:
  Try_to_get_file:
    uses: spsdevops/DevOps_Master/.github/workflows/reusable_get_file.yml@main
    secrets: inherit
permissions: write-all
